spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/java?allowPublicKeyRetrieval=true'
    username: root
    password: '@Zxcv9494'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: true
server:
  port: 9095